---
# Install GIT, Apache, PHP & Mysql

- name: Update all packages to their latest version
  apt:
    name: "*"
    state: latest

- name: Install GIT
  apt:
    name: git
    state: present

- name: Install Apache
  apt: "name=apache2 update_cache=yes state=latest"
  
- name: Install PHP
  apt: "name=php update_cache=yes state=latest"

- name: Install MYSQL
  apt: "name=mariadb-server update_cache=yes state=latest"

- name: Install Python3
  apt: "name=python3-venv"

- name: Install PIP
  apt: "name=python3-pip"

- name: Install PyOpenSSL
  pip:
    name: PyOpenSSL

- name: Install cryptography
  pip:
    name: cryptography
